### ISSUE TITLE
Debería poder reconocer rimas

### ISSUE THREAD

**Issue by lortega** [arnaldog/paya_generator_3000#1]
Sería genial si el paya generator 3000 pudiera elegir las combinaciones en base a los sufijos para poder formar rimas de paya.

**Comment by arnaldog** [comment]
Luis, @psbarrales  hizo un gran aporte en eso. :)
https://github.com/arnaldog/paya_generator_3000/pull/2

**Comment by erasmo-marin** [comment]
Falta que reconozca la acentuación de las palabras, ya que para que rime, ambas palabras deben tener el acento en la misma sílaba. También debería priorizar las rimas consonantes, y en caso de no encontrar, tirar una asonante.
